routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountsController;
use App\Http\Controllers\BrokersController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\DematsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\OrdersController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\StocksController;
use App\Http\Controllers\UsersController;

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function() {

    Route::get('/', [FrontendController::class, 'index'])->name('frontend.index');
    Route::get('/portfolio/{demat}', [PortfolioController::class, 'index'])->name('frontent.portfolio.index');
    Route::get('/account/{account}/demats', [DematsController::class, 'getDematsForAccount'])->name('account.demats');
    Route::get('orders/{demat_id}', [OrdersController::class, 'index'])->name('orders.index');
    Route::get('orders/{demat_id}/buy', [OrdersController::class, 'buyCreate'])->name('orders.buy');
    Route::get('orders/{demat_id}/sell/{stock_id}', [OrdersController::class, 'sellCreate'])->name('orders.sell');
    Route::post('orders/', [OrdersController::class, 'store'])->name('orders.store');
    Route::get('demats/all', [DematsController::class, 'displayAllDematsOfUser'])->name('demats.all');
    Route::get('change-password', [ChangePasswordController::class, 'index'])->name('changePassword.index');
    Route::post('change-password', [ChangePasswordController::class, 'store'])->name('change.password');
    Route::get('orders/{demat_id}/detailed', [OrdersController::class, 'indexDetailed'])->name('orders.index.detailed');
    Route::get('export/{demat_id}', [OrdersController::class, 'export'])->name('export');



    Route::resource('accounts', AccountsController::class);
    Route::resource('demats', DematsController::class);
    Route::resource('stocks', StocksController::class);
    // Route::resource('orders', OrdersController::class);
    Route::resource('users', UsersController::class);
    Route::resource('brokers', BrokersController::class);
});

app/Models/Broker.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Broker extends Model
{
    use HasFactory;
    protected $fillable = ['dp_name', 'broker_charges'];

    public function demats()
    {
        return $this->hasMany(Demat::class);
    }
}

app/Http/Controllers/BrokersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Brokers\CreateBrokerRequest;
use App\Http\Requests\Brokers\UpdateBrokerRequest;
use App\Models\Broker;
use App\Models\Demat;
use Illuminate\Http\Request;

class BrokersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $brokers = Broker::all();
        return view('brokers.index', compact('brokers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('brokers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateBrokerRequest $request)
    {
        Broker::create([
            'dp_name' => $request->dp_name,
            'broker_charges' => $request->broker_charges
        ]);
        session()->flash('success', 'Broker Added Successfully!');
        return redirect(route('brokers.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Broker $broker)
    {
        return view('brokers.edit', compact(['broker']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBrokerRequest $request, Broker $broker)
    {
        $broker->dp_name = $request->dp_name;
        $broker->broker_charges = $request->broker_charges;
        $broker->save();

        session()->flash('success','Broker updated successfully!');
        return redirect(route('brokers.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $broker = Broker::findorFail($id);
        $broker->delete();
        session()->flash('success', 'Broker Deleted Successfully!');
        return redirect(route('brokers.index'));
    }
}

resources/views/brokers/create.blade.php
@extends('layouts.admin-panel.app')
@section('head-name',"Brokers")
@section('main-content')
<div class="content">
    <div class="container-fluid">

        <div class="card">
            <div class="card-header"><h2>Add New Broker</h2></div>
            <div class="card-body">



                    <div class="form-group">
                        <label for="dp">DP Name</label>
                        <input type="text"
                                class="form-control @error('dp') is-invalid @enderror"
                                style="text-transform:uppercase"
                                id="dp"
                                value="{{ old('dp') }}"
                                placeholder="Enter DP Name"
                                onkeyup="setDpName()"
                                >

                    </div>

                    <div class="form-group">
                        <label for="dp">Type</label>
                        <select id="type" class="form-control" onchange="setDpName()">
                            <option value="1">Standard</option>
                            <option value="2">Deluxe</option>
                            <option value="3">Executive</option>
                        </select>
                        @error('type')
                          <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                <form action="{{ route('brokers.store') }}" method="POST">
                    @csrf

                    <div class="form-group">
                        <label for="dp_name">Dp Name constructed</label>
                        <input type="text"
                                class="form-control disabled"
                                id="dp_name"
                                value=""
                                name="dp_name"
                                >
                    </div>
                    @error('dp_name')
                                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror

                    <div class="form-group">
                        <label for="broker_charges">Broker Charges in %</label>
                        <input type="decimal"
                                class="form-control @error('broker_charges') is-invalid @enderror"
                                id="broker_charges"
                                value="{{ old('broker_charges') }}"
                                placeholder="Enter Broker Charges"
                                name="broker_charges">
                            @error('broker_charges')
                                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                            @enderror
                    </div>
                    <button type="submit" class="btn btn-outline-success">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('page-level-scripts')

<script>
    function setDpName()
    {
        dp = $("#dp").val();
        if(dp == "")
        {
            alert("Please give some dp name first");
            return;
        }
        type = $("#type").val().toUpperCase();
        $("#dp_name").attr("value",dp+" "+type);
    }
</script>

@endsection

resources/views/brokers/edit.blade.php
@extends('layouts.admin-panel.app')
@section('head-name',"Brokers")
@section('main-content')
<div class="content">
    <div class="container-fluid">

        <div class="card">
            <div class="card-header"><h2>Edit Broker</h2></div>
            <div class="card-body">



                    <div class="form-group">
                        <label for="dp">DP Name</label>
                        <input type="text"
                                class="form-control"
                                style="text-transform:uppercase"
                                id="dp"
                                placeholder="Enter DP Name"
                                onkeyup="setDpName()"
                                >
                    </div>

                    <div class="form-group">
                        <label for="dp">Type</label>
                        <select id="type" class="form-control" onchange="setDpName()">
                            <option value="1">Standard</option>
                            <option value="2">Deluxe</option>
                            <option value="3">Executive</option>
                        </select>
                        @error('type')
                          <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                <form action="{{ route('brokers.update', $broker->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="dp_name">Dp Name constructed</label>
                        <input type="text"
                                class="form-control disabled"
                                id="dp_name"
                                value="{{ $broker->dp_name }}"
                                name="dp_name"
                                >
                    </div>
                    @error('dp_name')
                                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror

                    <div class="form-group">
                        <label for="broker_charges">Broker Charges in %</label>
                        <input type="decimal"
                                class="form-control @error('broker_charges') is-invalid @enderror"
                                id="broker_charges"
                                value="{{ old('broker_charges', $broker->broker_charges) }}"
                                placeholder="Enter Broker Charges"
                                name="broker_charges">
                            @error('broker_charges')
                                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                            @enderror
                    </div>
                    <button type="submit" class="btn btn-outline-success">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('page-level-scripts')

<script>
    function setDpName()
    {
        dp = $("#dp").val().toUpperCase();
        type = $("#type").val();
        $("#dp_name").attr("value",dp+" "+type);
    }
</script>

@endsection

resources/views/brokers/index.blade.php
@extends('layouts.admin-panel.app')
@section('head-name',"Brokers")
@section('main-content')
<div class="content">
    <div class="container-fluid">

        <div class="d-flex justify-content-end mb-3">
            <a href="{{ route('brokers.create') }}" class="btn btn-outline-primary">Add Broker</a>
        </div>
        <div class="card">
            <div class="card-header"><h2>Brokers</h2></div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col-4">DP Name</th>
                            <th scope="col-4">Broker Charges</th>
                            <th scope="col-4">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($brokers as $broker)
                            <tr>
                                <td>{{ $broker->dp_name }}</td>
                                <td>{{ $broker->broker_charges }} %</td>
                                <td>
                                    <a href="{{ route('brokers.edit', $broker->id) }}" class="btn btn-sm btn-primary mr-2">Edit</a>
                                    <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $broker->id }})" data-toggle="modal" data-target="#deleteModal">
                                        Delete
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>


    </div>
</div>

<!-- DELETE MODAL -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Modal Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="POST" id="deleteBrokerForm">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    Are you sure, you want to delete this broker?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-danger">Delete Broker</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="mt-5">
    {{-- {{ $stocks->links('vendor.pagination.bootstrap-4') }} --}}
</div>
@endsection

@section('page-level-scripts')
    <script>
        function displayModal(brokerId){
            var url = "/brokers/" + brokerId;
            $("#deleteBrokerForm").attr('action', url);
        }
    </script>
@endsection