routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountsController;
use App\Http\Controllers\BrokersController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\DematsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\OrdersController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\StocksController;
use App\Http\Controllers\UsersController;

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function() {

    Route::get('/', [FrontendController::class, 'index'])->name('frontend.index');
    Route::get('/portfolio/{demat}', [PortfolioController::class, 'index'])->name('frontent.portfolio.index');
    Route::get('/account/{account}/demats', [DematsController::class, 'getDematsForAccount'])->name('account.demats');
    Route::get('orders/{demat_id}', [OrdersController::class, 'index'])->name('orders.index');
    Route::get('orders/{demat_id}/buy', [OrdersController::class, 'buyCreate'])->name('orders.buy');
    Route::get('orders/{demat_id}/sell/{stock_id}', [OrdersController::class, 'sellCreate'])->name('orders.sell');
    Route::post('orders/', [OrdersController::class, 'store'])->name('orders.store');
    Route::get('demats/all', [DematsController::class, 'displayAllDematsOfUser'])->name('demats.all');
    Route::get('change-password', [ChangePasswordController::class, 'index'])->name('changePassword.index');
    Route::post('change-password', [ChangePasswordController::class, 'store'])->name('change.password');
    Route::get('orders/{demat_id}/detailed', [OrdersController::class, 'indexDetailed'])->name('orders.index.detailed');
    Route::get('export/{demat_id}', [OrdersController::class, 'export'])->name('export');



    Route::resource('accounts', AccountsController::class);
    Route::resource('demats', DematsController::class);
    Route::resource('stocks', StocksController::class);
    // Route::resource('orders', OrdersController::class);
    Route::resource('users', UsersController::class);
    Route::resource('brokers', BrokersController::class);
});

app/Models/Stock.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Stock extends Model
{
    use HasFactory;
    protected $fillable = ['stock_name', 'closing_price'];

    public function orders()
    {
        return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/StocksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Stocks\CreateStockRequest;
use App\Http\Requests\Stocks\UpdateStockRequest;
use App\Models\Stock;
use Illuminate\Http\Request;

class StocksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stocks = Stock::all();
        return view('stocks.index', compact('stocks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('stocks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateStockRequest $request)
    {
        Stock::create([
            'stock_name' => $request->stock_name,
            'closing_price' => $request->closing_price
        ]);
        session()->flash('success', 'Stock Created Successfully!');
        return redirect(route('stocks.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Stock $stock)
    {
        return view('stocks.edit', compact(['stock']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateStockRequest $request, Stock $stock)
    {
        $stock->stock_name = $request->stock_name;
        $stock->closing_price = $request->closing_price;
        $stock->save();

        session()->flash('success','Stock updated successfully!');
        return redirect(route('stocks.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $stock = Stock::with('orders')->findorFail($id);
        // dd($stock->orders->count());
        if($stock->orders->count() != 0)
        {
            session()->flash('error', 'Stock cannot be Deleted!');
            return redirect(route('stocks.index'));
        }
        $stock->delete();
        session()->flash('success', 'Stock Deleted Successfully!');
        return redirect(route('stocks.index'));

        // if($stock->orders()->count() > 0){
        //     session()->flash('error','This Stock cannot be deleted!');
        //     return redirect(route('stocks.index'));
        // }
        // $stock->delete();


        // session()->flash('success','Stock deleted successfully!');
        // return redirect(route('stocks.index'));
    }
}

resources/views/stocks/create.blade.php
@extends('layouts.admin-panel.app')
@section('head-name',"Stocks")
@section('main-content')
<div class="content">
    <div class="container-fluid">

        <div class="card">
            <div class="card-header"><h2>Add New Stock</h2></div>
            <div class="card-body">
                <form action="{{ route('stocks.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="stock_name">Stock Name</label>
                        <input type="text"
                                class="form-control @error('stock_name') is-invalid @enderror"
                                id="stock_name"
                                value="{{ old('stock_name') }}"
                                placeholder="Enter Stock Name"
                                name="stock_name">
                            @error('stock_name')
                                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                            @enderror
                    </div>

                    <div class="form-group">
                        <label for="closing_price">Closing Price</label>
                        <input type="decimal"
                                class="form-control @error('closing_price') is-invalid @enderror"
                                id="closing_price"
                                value="{{ old('closing_price') }}"
                                placeholder="Enter Closing Price"
                                name="closing_price">
                            @error('closing_price')
                                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                            @enderror
                    </div>
                    <button type="submit" class="btn btn-outline-success">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/stocks/edit.blade.php
@extends('layouts.admin-panel.app')
@section('head-name',"Stocks")
@section('main-content')
<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header"><h2>Edit Stock</h2></div>
            <div class="card-body">
                <form action="{{ route('stocks.update', $stock->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="stock_name">Stock Name</label>
                        <input type="text"
                                class="form-control @error('stock_name') is-invalid @enderror"
                                id="stock_name"
                                value="{{ old('stock_name', $stock->stock_name) }}"
                                placeholder="Enter Stock Name"
                                name="stock_name">
                            @error('stock_name')
                                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                            @enderror
                    </div>

                    <div class="form-group">
                        <label for="closing_price">Closing Price</label>
                        <input type="number"
                                class="form-control @error('closing_price') is-invalid @enderror"
                                id="closing_price"
                                value="{{ old('closing_price', $stock->closing_price) }}"
                                placeholder="Enter Closing Price"
                                name="closing_price">
                            @error('closing_price')
                                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                            @enderror
                    </div>
                    <button type="submit" class="btn btn-outline-success">Submit</button>
                </form>
            </div>
        </div>

    </div>
</div>
@endsection

resources/views/stocks/index.blade.php
@extends('layouts.admin-panel.app')
@section('head-name',"Stocks")
@section('main-content')
<div class="content">
    <div class="container-fluid">

        <div class="d-flex justify-content-end mb-3">
            <a href="{{ route('stocks.create') }}" class="btn btn-outline-primary">Add Stock</a>
        </div>
        <div class="card">
            <div class="card-header"><h2>Stocks</h2></div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col-4">Stock Name</th>
                            <th scope="col-4">Closing Price</th>
                            <th scope="col-4">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($stocks as $stock)
                            <tr>
                                <td>{{ $stock->stock_name }}</td>
                                <td>{{ $stock->closing_price }}</td>
                                <td>
                                    <a href="{{ route('stocks.edit', $stock->id) }}" class="btn btn-sm btn-primary mr-2">Edit</a>
                                    <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $stock->id }})" data-toggle="modal" data-target="#deleteModal">
                                        Delete
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>


    </div>
</div>

<!-- DELETE MODAL -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Modal Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="POST" id="deleteStockForm">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    Are you sure, you want to delete this stock?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-danger">Delete Stock</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="mt-5">
    {{-- {{ $stocks->links('vendor.pagination.bootstrap-4') }} --}}
</div>
@endsection

@section('page-level-scripts')
    <script>
        function displayModal(stockId){
            var url = "/stocks/" + stockId;
            $("#deleteStockForm").attr('action', url);
        }
    </script>
@endsection