routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountsController;
use App\Http\Controllers\BrokersController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\DematsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\OrdersController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\StocksController;
use App\Http\Controllers\UsersController;

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function() {

    Route::get('/', [FrontendController::class, 'index'])->name('frontend.index');
    Route::get('/portfolio/{demat}', [PortfolioController::class, 'index'])->name('frontent.portfolio.index');
    Route::get('/account/{account}/demats', [DematsController::class, 'getDematsForAccount'])->name('account.demats');
    Route::get('orders/{demat_id}', [OrdersController::class, 'index'])->name('orders.index');
    Route::get('orders/{demat_id}/buy', [OrdersController::class, 'buyCreate'])->name('orders.buy');
    Route::get('orders/{demat_id}/sell/{stock_id}', [OrdersController::class, 'sellCreate'])->name('orders.sell');
    Route::post('orders/', [OrdersController::class, 'store'])->name('orders.store');
    Route::get('demats/all', [DematsController::class, 'displayAllDematsOfUser'])->name('demats.all');
    Route::get('change-password', [ChangePasswordController::class, 'index'])->name('changePassword.index');
    Route::post('change-password', [ChangePasswordController::class, 'store'])->name('change.password');
    Route::get('orders/{demat_id}/detailed', [OrdersController::class, 'indexDetailed'])->name('orders.index.detailed');
    Route::get('export/{demat_id}', [OrdersController::class, 'export'])->name('export');



    Route::resource('accounts', AccountsController::class);
    Route::resource('demats', DematsController::class);
    Route::resource('stocks', StocksController::class);
    // Route::resource('orders', OrdersController::class);
    Route::resource('users', UsersController::class);
    Route::resource('brokers', BrokersController::class);
});

app/Models/Demat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Demat extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public function account()
    {
        return $this->belongsTo(Account::class);
    }
    public function orders()
    {
        return $this->hasMany(Order::class);
    }
    public function broker()
    {
        return $this->belongsTo(Broker::class);
    }
    //Scopes
    public function scopeGetdematsbyaccount($query)
    {
        $accounts_id = Account::where('user_id',Auth::user()->id)->pluck('id')->toArray();
        $demats = $query->whereIn('account_id',$accounts_id);
        return  $demats;
    }
}

app/Http/Controllers/DematsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Demats\CreateDematRequest;
use App\Http\Requests\Demats\UpdateDematRequest;
use App\Models\Account;
use App\Models\Broker;
use App\Models\Demat;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DematsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $demats = Demat::all();
        return view('demats.index', compact('demats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $accounts = Account::where('user_id',Auth::user()->id)->get();
        $brokers = Broker::all();
        return view('demats.create', compact(['accounts','brokers']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateDematRequest $request)
    {
        $account = Account::findOrFail($request->account_id);
        Demat::create([
            'account_id' => $request->account_id,
            'dp_id' => $request->dp_id,
            'broker_id' => $request->broker_id,
            'dp_account_number' => $request->dp_account_number,
            'trading_account_number' => $request->trading_account_number,
            'total_invested' => 0,
            'total_market_value' => 0
        ]);
        session()->flash('success', 'Demat Created Successfully!');
        $demats = $account->demats;
        return view('demats.index', compact('demats'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Demat  $demat
     * @return \Illuminate\Http\Response
     */
    public function show(Demat $demat)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Demat  $demat
     * @return \Illuminate\Http\Response
     */
    public function edit(Demat $demat)
    {
        $brokers = Broker::all();
        return view('demats.edit', compact(['demat', 'brokers']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Demat  $demat
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateDematRequest $request, Demat $demat)
    {
        $demat->dp_id = $request->dp_id;
        $demat->broker_id = $request->broker_id;
        $demat->dp_account_number = $request->dp_account_number;
        $demat->trading_account_number = $request->trading_account_number;

        $demat->save();

        session()->flash('success','Demat updated successfully!');
        return redirect(route('account.demats', $demat->account_id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Demat  $demat
     * @return \Illuminate\Http\Response
     */
    public function destroy(Demat $demat)
    {
        if($demat->orders()->count() > 0){
            session()->flash('error','This Demat cannot be deleted as it has stocks!');
            return redirect(route('demats.index'));
        }
        $demat->delete();


        session()->flash('success','Demat deleted successfully!');
        return redirect(route('demats.index'));
    }

    public function getDematsForAccount(Request $request, Account $account)
    {
        $demats = $account->demats;
        return view('demats.index', compact('demats'));
    }

    public function displayAllDematsOfUser()
    {
        $demats = Demat::whereHas('account', function($query){
            $query->where('user_id', auth()->user()->id);
        })->get();
        return view('demats.viewAllDemats', compact('demats'));
    }
}

resources/views/demats/create.blade.php
@extends('layouts.admin-panel.app')

@section('page-level-styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endsection


@section('main-content')
    <div class="card">
        <div class="card-header"><h2>Add New Demat</h2></div>
        <div class="card-body">
            <form action="{{ route('demats.store') }}" method="POST">
                @csrf

                <div class="form-group">
                    <label for="account_id">Account</label>
                    <select name="account_id" id="account_id" class="form-control select2">
                        <option></option>
                        @foreach ($accounts as $account)
                            @if($account->id == old('account_id'))
                                <option value="{{ $account->id }}" selected>{{ $account->bank_account_number }}</option>
                            @else
                                <option value="{{ $account->id }}">{{ $account->bank_account_number }}</option>
                            @endif
                        @endforeach
                    </select>
                    @error('account_id')
                      <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="dp_id">Dp Id</label>
                    <input type="text"
                            class="form-control @error('dp_id') is-invalid @enderror"
                            id="dp_id"
                            value="{{ old('dp_id') }}"
                            placeholder="Enter Dp Id."
                            name="dp_id">
                        @error('dp_id')
                            <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                </div>

                <div class="form-group">
                    <label for="broker_id">Dp Name</label>
                    <select name="broker_id" id="broker_id" class="form-control select2">
                        <option></option>
                        @foreach ($brokers as $broker)
                            @if($broker->id == old('broker_id'))
                                <option value="{{ $broker->id }}" selected>{{ $broker->dp_name }}</option>
                            @else
                                <option value="{{ $broker->id }}">{{ $broker->dp_name }}</option>
                            @endif
                        @endforeach
                    </select>
                    @error('broker_id')
                      <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="dp_account_number">Dp Account Number</label>
                    <input type="text"
                            class="form-control @error('dp_account_number') is-invalid @enderror"
                            id="dp_account_number"
                            value="{{ old('dp_account_number') }}"
                            placeholder="Enter Dp Account Number."
                            name="dp_account_number">
                        @error('dp_account_number')
                            <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                </div>

                <div class="form-group">
                    <label for="trading_account_number">Trading Account Number</label>
                    <input type="text"
                            class="form-control @error('trading_account_number') is-invalid @enderror"
                            id="trading_account_number"
                            value="{{ old('trading_account_number') }}"
                            placeholder="Enter Trading Account Number."
                            name="trading_account_number">
                        @error('trading_account_number')
                            <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                </div>
                <form action="" method="GET" id="getDemats">
                    <input type="submit" class="btn btn-outline-primary" id="btn-demats" value="Submit">
                </form>
                {{-- <button type="submit" class="btn btn-outline-success">Submit</button> --}}
            </form>
        </div>
    </div>
@endsection
@section('page-level-scripts')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $('.select2').select2({
        placeholder: 'Select an option',
        allowClear: true
    });

    flatpickr("#published_at", {
        enableTime: true,
        dateFormat: "Y-m-d H:i"
    });

    $('.select2Demats').select2({
        placeholder: 'Select a Bank Account',
        allowClear: true
    });

    $('#btn-demats').click(function(e){
        // e.preventDefault();
        selectedId = $("#account_id").children('option:selected').val();
        if(selectedId == 0)
        {
            return;
        }

        var url = "/account/" + selectedId + "/demats";
        $("#getDemats").attr('action',url)
    });
</script>
@endsection

resources/views/demats/edit.blade.php
@extends('layouts.admin-panel.app')

@section('main-content')
    <div class="card">
        <div class="card-header"><h2>Edit Demat</h2></div>
        <div class="card-body">
            <form action="{{ route('demats.update', $demat->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="dp_id">Dp Id</label>
                    <input type="text"
                            class="form-control @error('dp_id') is-invalid @enderror"
                            id="dp_id"
                            value="{{ old('dp_id', $demat->dp_id) }}"
                            placeholder="Enter Dp Id."
                            name="dp_id">
                        @error('dp_id')
                            <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                </div>

                <div class="form-group">
                    <label for="broker_id">Dp Name</label>
                    <select name="broker_id" id="broker_id" class="form-control select2">
                        <option></option>
                        @foreach ($brokers as $broker)
                            @if($broker->id == old('broker_id', $demat->broker_id))
                                <option value="{{ $broker->id }}" selected>{{ $broker->dp_name }}</option>
                            @else
                                <option value="{{ $broker->id }}">{{ $broker->dp_name }}</option>
                            @endif
                        @endforeach
                    </select>
                    @error('broker_id')
                      <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="dp_account_number">Dp Account Number</label>
                    <input type="text"
                            class="form-control @error('dp_account_number') is-invalid @enderror"
                            id="dp_account_number"
                            value="{{ old('dp_account_number', $demat->dp_account_number ) }}"
                            placeholder="Enter Dp Account Number."
                            name="dp_account_number">
                        @error('dp_account_number')
                            <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                </div>

                <div class="form-group">
                    <label for="trading_account_number">Trading Account Number</label>
                    <input type="text"
                            class="form-control @error('trading_account_number') is-invalid @enderror"
                            id="trading_account_number"
                            value="{{ old('trading_account_number', $demat->trading_account_number) }}"
                            placeholder="Enter Trading Account Number."
                            name="trading_account_number">
                        @error('trading_account_number')
                            <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                </div>
                    <input type="submit" class="btn btn-outline-primary" id="btn-demats" value="Submit">
            </form>

        </div>
    </div>
@endsection
@section('page-level-scripts')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $('.select2').select2({
        placeholder: 'Select an option',
        allowClear: true
    });

    $('.select2Demats').select2({
        placeholder: 'Select a Bank Account',
        allowClear: true
    });
</script>
@endsection
@section('page-level-styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/demats/index.blade.php
@extends('layouts.admin-panel.app')
@section('head-name',"Demats")
@section('main-content')
<div class="content">
<div class="container-fluid">


    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('demats.create') }}" class="btn btn-outline-primary">Add Demat</a>
    </div>
    <div class="card">
        <div class="card-header"><h2>Demats</h2></div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Dp Id</th>
                        <th scope="col">Dp Name</th>
                        <th scope="col">Dp Account Number</th>
                        <th scope="col">Trading Account Number </th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($demats as $demat)
                        <tr>
                            <td>{{ $demat->dp_id }}</td>
                            <td>{{ $demat->broker->dp_name }}</td>
                            <td>{{ $demat->dp_account_number }}</td>
                            <td>{{ $demat->trading_account_number }}</td>
                            <td>
                                <a href="{{ route('demats.edit', $demat->id) }}" class="btn btn-sm btn-primary mr-2">Edit</a>
                                <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $demat->id }})" data-toggle="modal" data-target="#deleteModal">
                                    Delete
                                </button>
                                <a href="{{ route('frontent.portfolio.index', $demat->id) }}" class="btn btn-sm btn-success ml-2">View Portfolio</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

</div>
</div>
    <!-- DELETE MODAL -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Modal Title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="POST" id="deleteDematForm">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        Are you sure, you want to delete this Demat?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-danger">Delete Demat</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="mt-5">
        {{-- {{ $accounts->links('vendor.pagination.bootstrap-4') }} --}}
    </div>
@endsection

@section('page-level-scripts')
    <script>
        function displayModal(dematID){
            var url = "/demats/" + dematID;
            $("#deleteDematForm").attr('action', url);
        }
    </script>
@endsection

resources/views/demats/viewAllDemats.blade.php
@extends('layouts.admin-panel.app')
@section('head-name',"Demats")
@section('main-content')
<div class="content">
<div class="container-fluid">
    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('demats.create') }}" class="btn btn-outline-primary">Add Demat</a>
    </div>
    <div class="card">
        <div class="card-header"><h2>Demat Accounts of {{ Auth::user()->name }}</h2></div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Bank Account Number</th>
                        <th scope="col">Bank Name</th>
                        <th scope="col">Dp Id</th>
                        <th scope="col">Dp Name</th>
                        <th scope="col">Dp Account Number</th>
                        <th scope="col">Trading Account Number </th>
                        <th scope="col">Actions </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($demats as $demat)
                        <tr>
                            <td>{{ $demat->account->bank_account_number }}</td>
                            <td>{{ $demat->account->bank_name }}</td>
                            <td>{{ $demat->dp_id }}</td>
                            <td>{{ $demat->broker->dp_name }}</td>
                            <td>{{ $demat->dp_account_number }}</td>
                            <td>{{ $demat->trading_account_number }}</td>
                            <td>
                                <a href="{{ route('demats.edit', $demat->id) }}" class="btn btn-sm btn-primary mr-2">Edit</a>
                                <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $demat->id }})" data-toggle="modal" data-target="#deleteModal">
                                    Delete
                                </button>
                                <a href="{{ route('frontent.portfolio.index', $demat->id) }}" class="btn btn-sm btn-success ml-2">View Portfolio</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

</div>
</div>
    <div class="mt-5">
        {{-- {{ $demats->links('vendor.pagination.bootstrap-4') }} --}}
    </div>
@endsection