routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountsController;
use App\Http\Controllers\BrokersController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\DematsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\OrdersController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\StocksController;
use App\Http\Controllers\UsersController;

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function() {

    Route::get('/', [FrontendController::class, 'index'])->name('frontend.index');
    Route::get('/portfolio/{demat}', [PortfolioController::class, 'index'])->name('frontent.portfolio.index');
    Route::get('/account/{account}/demats', [DematsController::class, 'getDematsForAccount'])->name('account.demats');
    Route::get('orders/{demat_id}', [OrdersController::class, 'index'])->name('orders.index');
    Route::get('orders/{demat_id}/buy', [OrdersController::class, 'buyCreate'])->name('orders.buy');
    Route::get('orders/{demat_id}/sell/{stock_id}', [OrdersController::class, 'sellCreate'])->name('orders.sell');
    Route::post('orders/', [OrdersController::class, 'store'])->name('orders.store');
    Route::get('demats/all', [DematsController::class, 'displayAllDematsOfUser'])->name('demats.all');
    Route::get('change-password', [ChangePasswordController::class, 'index'])->name('changePassword.index');
    Route::post('change-password', [ChangePasswordController::class, 'store'])->name('change.password');
    Route::get('orders/{demat_id}/detailed', [OrdersController::class, 'indexDetailed'])->name('orders.index.detailed');
    Route::get('export/{demat_id}', [OrdersController::class, 'export'])->name('export');



    Route::resource('accounts', AccountsController::class);
    Route::resource('demats', DematsController::class);
    Route::resource('stocks', StocksController::class);
    // Route::resource('orders', OrdersController::class);
    Route::resource('users', UsersController::class);
    Route::resource('brokers', BrokersController::class);
});

resources/views/layouts/admin-panel/_content.blade.php
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <button type="button" class="btn btn-outline-primary">View Orders</button>
            </div>
            <div class="col-md-6">
                <div class="operation-buttons pull-right">
                    <button type="button" class="btn btn-outline-success">Buy</button>
                    <button type="button" class="btn btn-outline-danger">Sell</button>
                </div>
            </div>
        </div>
        <div class="row d-flex justify-content-center">


                    <div class="w-50 align-bottom">

                        <div class="card text-center ">
                            <div class="card-header">
                                <!-- Example split danger button -->
                                <div class="btn-group">

                                    <button type="button" class="btn btn-outline-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Bank Account <span class="sr-only">Toggle Dropdown</span>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="#"> Action</a>
                                    </div>
                                        <span>&nbsp &nbsp &nbsp</span>
                                </div>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-outline-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Demat Account <span class="sr-only">Toggle Dropdown</span>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="#">Next Action</a>
                                    </div>
                                        <span>&nbsp &nbsp &nbsp</span>
                                </div>
                            </div>
                            <div class="card-body">
                                <a href="#" class="btn btn-outline-primary">View Portfolio</a>
                            </div>
                        </div>

                </div>


        </div>
    </div>
</div>

resources/views/layouts/admin-panel/_footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <nav>
            <ul class="footer-menu">
                <li>
                    <a href="{{ route('frontend.index') }}">
                        Home
                    </a>
                </li>
            </ul>
            <p class="copyright text-justify-center">
                ©
                <script>
                    document.write(new Date().getFullYear())
                </script>
                <a href="@">SPY Team</a>, EK dusre ki help karo!!
            </p>
        </nav>
    </div>
</footer>

resources/views/layouts/admin-panel/_navigation.blade.php
    <nav class="navbar navbar-expand-lg " color-on-scroll="500">
        <div class="container-fluid">
            <a class="navbar-brand" href="#pablo"> @yield('head-name') </a>
            <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar burger-lines"></span>
                <span class="navbar-toggler-bar burger-lines"></span>
                <span class="navbar-toggler-bar burger-lines"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navigation">
                @if(Auth::check())
                <ul class="navbar-nav mr-5">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="no-icon">{{ Auth::user()->name }}</span>
                        </a>
                        <div class="dropdown-menu " aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{{ route('users.index') }}">Profile</a> {{--edit user, change password--}}
                            <div class="divider"></div>
                            <form action="{{ route('logout') }}" method="POST">
                                @csrf
                                <button class="dropdown-item" type="submit">Logout</button>
                            </form>
                        </div>
                    </li>
                </ul>
                @else
                <ul class="navbar-nav mr-5">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">
                            <span class="no-icon">Login</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">
                            <span class="no-icon">Register</span>
                        </a>
                    </li>
                </ul>
                @endif
            </div>
        </div>
    </nav>

resources/views/layouts/admin-panel/_sidebar.blade.php
<div class="sidebar" data-image="{{ asset('frontend/assets/img/sidebar-5.jpg') }}">
    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="#"class="simple-text">
                Stock-Book
            </a>
        </div>
        <ul class="nav">
            <li class="nav-item {{ request()->path() === '/' ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('frontend.index') }}">
                    <i class="nc-icon nc-chart-pie-35"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li class="nav-item {{ request()->path() === 'accounts' ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('accounts.index') }}">
                    <i class="nc-icon nc-circle-09"></i>
                    <p>Bank Accounts</p>
                </a>
            </li>
            <li class="nav-item {{ request()->path() === 'stocks' ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('stocks.index') }}">
                    <i class="nc-icon nc-paper-2"></i>
                    <p>Stocks</p>
                </a>
            </li>
            <li class="nav-item {{ request()->path() === 'demats' ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('demats.all') }}">
                    <i class="nc-icon nc-credit-card"></i>
                    <p>Demats</p>
                </a>
            </li>

            <li class="nav-item {{ request()->path() === 'brokers' ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('brokers.index') }}">
                    <i class="nc-icon nc-notes"></i>
                    <p>Brokers</p>
                </a>
            </li>
        </ul>
    </div>
</div>

resources/views/layouts/admin-panel/app.blade.php
{{-- <html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ asset('admin-panel/css/bootstrap.min.css') }}" crossorigin="anonymous">
    @yield('page-level-styles')
    <title>Hello, world!</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{{ route('dashboard') }}">Stock Book Admin Panel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


       <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <ul class="navbar-nav ml-auto">
               <li class="nav-item dropdown">
                   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                       {{ auth()->user()->name }}
                   </a>
                   <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                       <form action="{{ route('logout') }}" method="POST">
                           @csrf
                           <input type="submit" class="dropdown-item" value="Logout">
                       </form>

                   </div>
               </li>
           </ul>
       </div>
   </div>
</nav>
<div class="container py-5">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a href="{{ route('dashboard') }}">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('accounts.index') }}">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('demats.index') }}">Demats</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('stocks.index') }}">Stocks</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('orders.index') }}">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            @include('layouts.partials._message')
            @yield('content')
        </div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{{ asset('admin-panel/js/bootstrap.min.js') }}" ></script>

@yield('page-level-scripts')
</body>
</html> --}}


<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8" />
    {{--Images to be linked  --}}
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('frontend/assets/img/apple-icon.png') }}">
    <link rel="icon" type="image/png" href="{{ asset('frontend/assets/img/favicon.ico') }}">
    {{-- Important Meta Tags --}}
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    {{-- Title goes here --}}
    <title>@yield('title')</title>
    <!-- Fonts and icons -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="{{ asset('frontend/assets/css/bootstrap.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('frontend/assets/css/light-bootstrap-dashboard.css?v=2.0.0') }}" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{{ asset('frontend/assets/css/demo.css') }}" rel="stylesheet" />
    <link href="{{ asset('/css/custom-style.css') }}" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" />

    @yield('page-level-styles')
</head>

<body>
    <div class="wrapper">
        @include('layouts.admin-panel._sidebar')
        <div class="main-panel">
            <!-- Navbar -->
            @include('layouts.admin-panel._navigation')

            <div class="col-md-12">
                @include('layouts.partials._message')
            </div>

            @yield('main-content')

            {{-- Footer --}}
            @include('layouts.admin-panel._footer')
        </div>
    </div>

</body>
<!--   Core JS Files   -->
<script src="{{ asset('frontend/assets/js/core/jquery.3.2.1.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('frontend/assets/js/core/popper.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('frontend/assets/js/core/bootstrap.min.js') }}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{{ asset('frontend/assets/js/plugins/bootstrap-switch.js') }}"></script>
<!--  Chartist Plugin  -->
{{-- <script src="{{ asset('frontend/assets/js/plugins/chartist.min.js') }}"></script> --}}
<!--  Notifications Plugin    -->
<script src="{{ asset('frontend/assets/js/plugins/bootstrap-notify.js') }}"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="{{ asset('frontend/assets/js/light-bootstrap-dashboard.js?v=2.0.0') }}" type="text/javascript"></script>
<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->
<script src="{{ asset('frontend/assets/js/demo.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        // Javascript method's body can be found in assets/js/demos.js
        // demo.initDashboardPageCharts();
    });
</script>
@yield('page-level-scripts')
</html>